ARG NODE_VERSION=22-alpine

FROM node:${NODE_VERSION} AS builder

WORKDIR /app

COPY . .

RUN yarn install
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

FROM node:${NODE_VERSION} AS production

WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/dist/
COPY --from=builder /app/packages/client/server/ /app/server/
COPY --from=builder /app/packages/client/package.json /app/package.json

RUN yarn install --production=true

EXPOSE 80
CMD [ "node", "/app/server/index.js" ]
