ARG NODE_VERSION=22-alpine

FROM node:${NODE_VERSION} AS builder

WORKDIR /app

ARG EXTERNAL_SERVER_URL
ARG INTERNAL_SERVER_URL

ENV EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL}
ENV INTERNAL_SERVER_URL=${INTERNAL_SERVER_URL}

COPY . .

RUN yarn install --frozen-lockfile --network-timeout 600000 --ignore-engines --prefer-offline --no-progress

RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

FROM node:${NODE_VERSION} AS production

WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/dist/
COPY --from=builder /app/packages/client/server/ /app/server/
COPY --from=builder /app/packages/client/package.json /app/package.json
COPY --from=builder /app/yarn.lock /app/yarn.lock

RUN yarn install --production=true --frozen-lockfile --network-timeout 600000 --ignore-engines --prefer-offline --no-progress

EXPOSE 80

CMD [ "node", "/app/server/index.js" ]
