ARG NODE_VERSION=22-alpine

FROM node:${NODE_VERSION} AS builder

WORKDIR /app

ARG EXTERNAL_SERVER_URL
ARG INTERNAL_SERVER_URL

ENV EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL}
ENV INTERNAL_SERVER_URL=${INTERNAL_SERVER_URL}

COPY package.json yarn.lock lerna.json ./
COPY packages/client/package.json packages/client/
COPY packages/client/tsconfig.json packages/client/
COPY packages/server/package.json packages/server/

RUN yarn install --frozen-lockfile --network-timeout 600000 --ignore-engines --prefer-offline --no-progress

COPY packages/client/ packages/client/
COPY packages/server/ packages/server/

RUN yarn build --scope=client

FROM node:${NODE_VERSION} AS production

WORKDIR /app

COPY package.json yarn.lock ./
COPY packages/client/package.json packages/client/

RUN yarn install --production=true --frozen-lockfile --prefer-offline --no-progress --network-timeout 600000

COPY --from=builder /app/packages/client/dist/ /app/dist/
COPY --from=builder /app/packages/client/server/ /app/server/

EXPOSE 80

CMD [ "node", "/app/server/index.js" ]
