services:
  postgres:
    image: postgres:14-alpine
    container_name: re-play-postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_network

  client:
    container_name: prakticum-client

    image: prakticum-client

    depends_on:
      server:
        condition: service_healthy

    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        EXTERNAL_SERVER_URL: ${EXTERNAL_SERVER_URL}
        INTERNAL_SERVER_URL: ${INTERNAL_SERVER_URL}

    restart: unless-stopped

    ports:
      - "${CLIENT_PORT}:80"

    environment:
      PORT: 80
      NODE_ENV: production
      INTERNAL_SERVER_URL: ${INTERNAL_SERVER_URL}
      EXTERNAL_SERVER_URL: ${EXTERNAL_SERVER_URL}
    networks:
      - app_network

  server:
    container_name: prakticum-server

    image: prakticum-server

    depends_on:
      postgres:
        condition: service_healthy

    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}

    env_file:
      - .env

    restart: always

    environment:
      SERVER_PORT: ${SERVER_PORT}

    healthcheck:
      test:
        [
          'CMD-SHELL',
          "wget -qO- http://localhost:${SERVER_PORT}/health || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - app_network


networks:
    app_network:
        driver: bridge

volumes:
    postgres_data: