ARG NODE_VERSION=22-alpine

FROM node:${NODE_VERSION} AS builder

WORKDIR /app

COPY . .

RUN yarn install
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server

FROM node:${NODE_VERSION} AS production

WORKDIR /app

COPY --from=builder /app/packages/server/dist/ /app/
COPY --from=builder /app/packages/server/package.json /app/package.json

RUN yarn install --production=true

EXPOSE 3001
CMD [ "node", "/app/index.js" ]
